Emploi du temps

- create time table without a prof that has the same class, the same day.
    replaces zeros
    shuffle and retain
    search bad cases
    return zeros



In [131]:
import numpy as np

def init_class(subjects_table):

    # data processing. turn all 0 valued elements to different negative valued.
    for i, item in enumerate(array):
        if(item==0):
            array[i] = -i
    
    
    # hold the good elements. the 3-different-elements, dont want same subject in the same day.
    array_hold = []
    arraym = array.copy()
    for i in range(1000):

        # see if there still a possibility to get uniques. It is there if only the most occured element dont exceed the 
        # the third of the length of the array. if there is not a possiblity then reinit the array and the hold array.
        foo, counts = np.unique(arraym, return_counts=True)
        max = np.max(counts)
        cant_get_uniques = max > (len(arraym) / 3)
        if(cant_get_uniques):
            arraym = array.copy()
            array_hold = []

        # choose three different elements. 
        for j in range(1000):
            choice = np.random.choice(arraym, 3, replace=False)
            unique = choice.shape[0] == np.unique(choice).shape[0]
            if(unique):
                array_hold.append(choice)
                break

        # remove those elements from the list
        for e in choice:
            arraym.remove(e)

        # if the array is empty then stop
        if(len(arraym) == 0):
            break
            
    # unprocess data
    array_hold = [item for sublist in array_hold for item in sublist]
    for i, item in enumerate(array_hold):
        if(item<0):
            array_hold[i] = 0
    
    array_hold = np.array(array_hold).reshape(-1, 3)
    return np.array(array_hold)

def init_days(classes_table):
    
    days_table = [classes_table[:,i] for i in range(5)]
    days_table = np.array(days_table)
    
    
    def day_is_bad(day):
        bad = False
        for hour, foo in enumerate(day):
            hour_table = day[:,hour]
            bad = hour_table.shape[0] != np.unique(hour_table).shape[0]
            
            # see if the repeating aren't zero. Remember zero can teach the same class the same day.
            arel, arco = np.unique(hour_table, return_counts=True)
            for i, item in enumerate(arel):
                if(item == 0):
                    if(arco[i]>=2):
                        bad = False
            
            if(bad):
                break

        return bad
    
    
    for day in days_table:
        bad = day_is_bad(day)
        if(bad):
            for i in range(3):
                np.random.shuffle(day[i])
                bad = day_is_bad(day)
                if(not bad or i == 3):
                    break
                    
    return days_table

In [139]:
array = [1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0]

# init class until they have one day off
for i in range(10):
    stop = False
    class_table = init_class(array)
    for day in class_table:
        if(np.sum(day) == 0):
            print(class_table)
            stop = True
    if(stop):
        break

[[0 0 0]
 [0 3 1]
 [1 3 0]
 [0 2 6]
 [0 2 1]
 [5 2 4]]
